name: Publish VSIX Extension

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Create GitHub Deployment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DEPLOYMENT_ID=$(gh api repos/${{ github.repository }}/deployments \
            -f ref=${{ github.sha }} \
            -f environment=production \
            -f required_contexts='[]' \
            --jq '.id')

      - name: Publish release to marketplace
        id: publish
        uses: mrluje/vs-marketplace-publisher@v2
        with:
          pat: ${{ secrets.vs_pat }}
          manifestPath: .marketplace/publishManifest.json
          useLatestReleaseAsset: true
      
      - name: Update Deployment Status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/deployments/${{ env.DEPLOYMENT_ID }}/statuses \
            -f state=success \
            -f environment_url=https://marketplace.visualstudio.com/items?itemName=ViktarKarpach.DebugAttachManager2022